import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# Read data generated by infinite data collection
file_path = os.path.join(os.path.expanduser("~"), "Desktop", "mesh_realtime_processed.csv")
df = pd.read_csv(file_path)

# Only use successfully received data
# Simulate continuous data acquisition + Mesh transmission
df = df[df["status"] == "Received"]
df = df.dropna(subset=["temperature_smooth", "humidity_smooth", "pressure_smooth"])

# Antifreeze detection threshold
FROST_THRESHOLD = 2.0

# Add antifreeze test results
df["frost_status"] = np.where(
    df["temperature_smooth"] <= FROST_THRESHOLD,
    "FROST_WARNING",
    "NORMAL"
)

# Select the data from the latest time point
latest_time = df["timestamp"].iloc[-1]
snapshot = df[df["timestamp"] == latest_time]

print("Using timestamp:", latest_time)
print(snapshot)

# IDW interpolation function
def idw_interpolation(x, y, points, value_column, power=2):  # (x, y): The location of the calculation # points: Node data # value_column: The variable to be interpolated
    numerator = 0
    denominator = 0

    for _, row in points.iterrows():
        distance = np.sqrt((x - row["x"])**2 + (y - row["y"])**2)  # Calculate distance

        if distance == 0:
            return row[value_column]

        weight = 1 / (distance ** power)  # Smaller distance → Larger weight
        numerator += weight * row[value_column]  # weighted average
        denominator += weight

    return numerator / denominator  # Interpolated average

# Creating a spatial grid
grid_x = np.linspace(0, 10, 100)
grid_y = np.linspace(0, 10, 100)

# Create a plotting function to avoid writing it three times
def plot_idw_heatmap(value_column, title, colorbar_label):
    heatmap = np.zeros((len(grid_y), len(grid_x)))

    # Perform IDW for each grid point
    for i, y in enumerate(grid_y):
        for j, x in enumerate(grid_x):
            heatmap[i, j] = idw_interpolation(x, y, snapshot, value_column)

    # Draw a heatmap
    plt.figure(figsize=(8, 6))

    plt.imshow(
        heatmap,
        extent=(0, 10, 0, 10),
        origin="lower",
        aspect="auto"
    )

    plt.colorbar(label=colorbar_label)

    # If it's a temperature heatmap, add frost threshold area lines
    if value_column == "temperature_smooth":
        plt.contour(
            grid_x,
            grid_y,
            heatmap,
            levels=[FROST_THRESHOLD],
            colors="red",
            linewidths=2
        )

    # Mark node position
    for _, row in snapshot.iterrows():
        plt.scatter(row["x"], row["y"], color="black", s=80)
        plt.text(row["x"] + 0.2, row["y"] + 0.2, row["node_id"], color="black")

        # If this node is at risk of frost, it will be highlighted in red
        if value_column == "temperature_smooth" and row["frost_status"] == "FROST_WARNING":
            plt.scatter(row["x"], row["y"], color="red", s=150, marker="x")

    plt.title(title)
    plt.xlabel("X Position")
    plt.ylabel("Y Position")

    plt.tight_layout()
    plt.show()


# Temperature Heatmap
plot_idw_heatmap(
    "temperature_smooth",
    "IDW Temperature Heatmap with Frost Detection",
    "Estimated Temperature (°C)"
)

# Humidity Heatmap
plot_idw_heatmap(
    "humidity_smooth",
    "IDW Humidity Heatmap from Mesh Gateway Data",
    "Estimated Humidity (%)"
)

# Air Pressure Heatmap
plot_idw_heatmap(
    "pressure_smooth",
    "IDW Pressure Heatmap from Mesh Gateway Data",
    "Estimated Pressure (hPa)"
)


df["timestamp"] = pd.to_datetime(df["timestamp"])

# Temperature graph
plt.figure(figsize=(12, 6))

for node_id in df["node_id"].unique():
    node_data = df[df["node_id"] == node_id]
    plt.plot(node_data["timestamp"], node_data["temperature_smooth"], label=node_id)

# Mark frost points
frost_points = df[df["frost_status"] == "FROST_WARNING"]

plt.scatter(
    frost_points["timestamp"],
    frost_points["temperature_smooth"],
    color="red",
    label="Frost Warning",
    zorder=3
)

# Frost Threshold Line
plt.axhline(
    y=FROST_THRESHOLD,
    color="gray",
    linestyle="--",
    label="Frost Threshold (2°C)"
)

plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.title("Multi-node Temperature with Frost Detection")
plt.xticks(df["timestamp"][::40], rotation=45)
plt.legend()
plt.tight_layout()
plt.show()


# Humidity graph
plt.figure(figsize=(12, 6))

for node_id in df["node_id"].unique():
    node_data = df[df["node_id"] == node_id]
    plt.plot(node_data["timestamp"], node_data["humidity_smooth"], label=node_id)

plt.xlabel("Time")
plt.ylabel("Humidity (%)")
plt.title("Multi-node Humidity")
plt.xticks(df["timestamp"][::40], rotation=45)
plt.legend()
plt.tight_layout()
plt.show()


# Barometric Pressure Chart
plt.figure(figsize=(12, 6))

for node_id in df["node_id"].unique():
    node_data = df[df["node_id"] == node_id]
    plt.plot(node_data["timestamp"], node_data["pressure_smooth"], label=node_id)

plt.xlabel("Time")
plt.ylabel("Pressure (hPa)")
plt.title("Multi-node Pressure")
plt.xticks(df["timestamp"][::40], rotation=45)
plt.legend()
plt.tight_layout()
plt.show()